#!/bin/sh
# Builds the simulator harness (sim/main.m): JamesDSP.x generated by logos with the internal generator as
# the tweak builds it, its settings and libraries, and SGDSPEngine.m over the simulator build of libjamesdsp
# (vendor/libjamesdsp, made here first), in an app whose main executable is the harness, so the rebinding
# of AudioOutputUnitStart takes as it does in Spotify.
#   THEOS=$HOME/theos ./build-sim.sh
set -e
cd "$(dirname "$0")"
SRC=../../tweak/Sources
VENDOR=../../vendor/libjamesdsp
OUT=build/sim
make -s -C "$VENDOR" JDSP_PLATFORM=sim -j8
rm -rf "$OUT"
mkdir -p "$OUT/gen" "$OUT/JamesDSPHarness.app"
"$THEOS/bin/logos.pl" -c generator=internal "$SRC/Shared/JamesDSP/JamesDSP.x" > "$OUT/gen/JamesDSP.m"
SDK=$(xcrun --sdk iphonesimulator --show-sdk-path)
xcrun -sdk iphonesimulator clang -target arm64-apple-ios17.0-simulator -fobjc-arc -g -O1 -isysroot "$SDK" -Wno-deprecated-declarations \
    -I"$SRC" -I"$SRC/Shared/JamesDSP" -isystem "$VENDOR/subtree/Main/libjamesdsp/jni/jamesdsp/jdsp" -isystem "$VENDOR" \
    sim/main.m "$OUT/gen/JamesDSP.m" "$SRC/Shared/JamesDSP/JamesDSPSettings.m" "$SRC/Shared/JamesDSP/JamesDSPFiles.m" \
    "$SRC/Shared/JamesDSP/SGDSPEngine.m" "$SRC/Core/SGRebind.m" "$SRC/Core/SGLog.m" "$SRC/Core/SGPrefs.m" \
    "$VENDOR/build/sim/libjamesdsp.a" \
    -framework UIKit -framework AudioToolbox -framework AVFoundation -framework Foundation \
    -o "$OUT/JamesDSPHarness.app/JamesDSPHarness"
cat > "$OUT/JamesDSPHarness.app/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>CFBundleExecutable</key><string>JamesDSPHarness</string>
<key>CFBundleIdentifier</key><string>com.vojta.jamesdspharness</string>
<key>CFBundleName</key><string>JamesDSPHarness</string>
<key>CFBundleVersion</key><string>1</string>
<key>CFBundleShortVersionString</key><string>1.0</string>
<key>UILaunchScreen</key><dict/>
<key>UIApplicationSceneManifest</key><dict><key>UIApplicationSupportsMultipleScenes</key><false/></dict>
</dict></plist>
PLIST
echo "built $OUT/JamesDSPHarness.app"
