#!/bin/sh
# Builds the simulator harness (sim/main.m): MusicHaptics.x generated by logos with the internal generator as the
# tweak builds it, the analyzer, the Vibrations settings and the Settings/ framework, fakehaptics.m in place of
# CoreHaptics.framework, in an app whose main executable is the harness, so the rebinding of AudioOutputUnitStart
# takes as it does in Spotify.
#   THEOS=$HOME/theos ./build-sim.sh
#   THEOS=$HOME/theos ./build-sim.sh before <dir>   the same against <dir>/MusicHaptics.x, <dir>/Haptics.h and
#                                                   <dir>/SGMusicAnalyzer.{h,m} of an older commit, format steps only
set -e
cd "$(dirname "$0")"
SRC=../../tweak/Sources
OUT=build/sim
HAPTICS="$SRC/Shared/Haptics"
EXTRA=""
SETTINGS="$SRC/Shared/Haptics/HapticsSettings.m $SRC/Shared/Haptics/SGFeedback.m $SRC/Settings/SGPage.m $SRC/Settings/SGPageStyle.m $SRC/Settings/SGModPage.m $SRC/Settings/SGGlowSwitch.m"
if [ "$1" = before ]; then
    HAPTICS=$2
    OUT=build/sim-before
    EXTRA="-DBEFORE -I$HAPTICS"
    SETTINGS=""
fi
rm -rf "$OUT"
mkdir -p "$OUT/gen" "$OUT/HapticsHarness.app"
"$THEOS/bin/logos.pl" -c generator=internal "$HAPTICS/MusicHaptics.x" > "$OUT/gen/MusicHaptics.m"
SDK=$(xcrun --sdk iphonesimulator --show-sdk-path)
xcrun -sdk iphonesimulator clang -target arm64-apple-ios17.0-simulator -fobjc-arc -g -O1 -isysroot "$SDK" -Wno-deprecated-declarations \
    $EXTRA -I"$SRC" -I"$SRC/Shared/Haptics" -Isim \
    sim/main.m sim/fakehaptics.m "$OUT/gen/MusicHaptics.m" "$HAPTICS/SGMusicAnalyzer.m" $SETTINGS \
    "$SRC/Core/SGRebind.m" "$SRC/Core/SGLog.m" "$SRC/Core/SGPrefs.m" "$SRC/Core/SGUIMode.m" "$SRC/Core/SGViewTree.m" "$SRC/Core/SGFlagForce.m" \
    -framework UIKit -framework QuartzCore -framework CoreGraphics -framework AudioToolbox -framework AVFoundation -framework Foundation \
    -o "$OUT/HapticsHarness.app/HapticsHarness"
cat > "$OUT/HapticsHarness.app/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>CFBundleExecutable</key><string>HapticsHarness</string>
<key>CFBundleIdentifier</key><string>com.vojta.hapticsharness</string>
<key>CFBundleName</key><string>HapticsHarness</string>
<key>CFBundleVersion</key><string>1</string>
<key>CFBundleShortVersionString</key><string>1.0</string>
<key>UILaunchScreen</key><dict/>
<key>UIApplicationSceneManifest</key><dict><key>UIApplicationSupportsMultipleScenes</key><false/></dict>
</dict></plist>
PLIST
echo "built $OUT/HapticsHarness.app"
